---
kind: pipeline
type: exec
name: default1

platform:
  os: linux
  arch: amd64

steps:
- name: tag
  commands:
  - env
  
trigger:
  event:
  - tag

---
kind: pipeline
type: exec
name: default2

platform:
  os: linux
  arch: amd64

steps:
- name: all
  commands:
  - env
